name: minigolf
channels:
  - delichon
  - defaults
dependencies:
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - openssl=1.1.1f
  - pip=20.0.2
  - pygame=1.9.6
  - python=3.7.7
  - setuptools=46.1.3
  - sqlite=3.31.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2

